/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mytest_MainActivity_PlaceholderFragment */

#ifndef _Included_com_example_mytest_MainActivity_PlaceholderFragment
#define _Included_com_example_mytest_MainActivity_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
